import express from "express";
import adminRoute from "./admin/admin.route.js";        
import emailSettingRoute from "./admin/emailSetting.route.js";
import counterRoute from "./admin/counter.route.js";
import coreServicesRoute from "./admin/coreServices.route.js";
import specialityRoute from "./admin/speciality.route.js";
import disorderRoute from "./admin/disorder.route.js";
import disorderSectionRoute from "./admin/disorderSection.route.js";
import cashlessRoute from "./admin/cashless.route.js";
import patientReviewRoute from "./admin/patientReview.route.js";
import healthInfoRoute from "./admin/healthInfo.route.js";
import featureRoute from "./admin/feature.route.js";
import ourTeamRoute from "./admin/ourTeam.route.js";
import doctorDetailsRoute from "./admin/doctorDetails.route.js";
import gallaryTitleRoute from "./admin/gallaryTitle.route.js";
import gallaryImageRoute from "./admin/gallaryImage.route.js";
import gallaryCategoryRoute from "./admin/gallaryCategory.route.js";
import inquiryRoute from "./admin/inquiry.route.js";
import aboutImageRoute from "./admin/aboutImage.route.js";
import aboutTabsRoute from "./admin/aboutTabs.route.js";
import aboutSectionRoute from "./admin/aboutSection.route.js";
import missionvisionRoute from "./admin/missionVision.route.js";
import menuRoute from "./admin/menu.route.js";
import bannerRoute from "./admin/banner.route.js";
import websiteSetting from "./admin/websiteSetting.route.js";
import careerRoute from "./admin/career.route.js";
import tieUpTitleRoute from "./admin/tieUpTitle.route.js";
import tieUpImageRoute from "./admin/tieUpImage.route.js";
import bloodDonationRoute from "./admin/bloodDonation.route.js";
import coreFacilitiesRoute from "./admin/coreFacilities.route.js";
import homePageBannerRoute from "./admin/homePageBanner.route.js";

const router = express.Router();

router.use("/admin", adminRoute);
router.use("/emailSetting", emailSettingRoute);
router.use("/counter", counterRoute);
router.use("/coreServices", coreServicesRoute);
router.use("/speciality", specialityRoute);
router.use("/disorder", disorderRoute);
router.use("/disorderSection", disorderSectionRoute);
router.use("/cashless", cashlessRoute);
router.use("/patientReview", patientReviewRoute);
router.use("/healthInfo", healthInfoRoute);
router.use("/feature", featureRoute);
router.use("/ourTeam", ourTeamRoute);
router.use("/doctorDetails", doctorDetailsRoute);
router.use("/gallaryTitle", gallaryTitleRoute);
router.use("/gallaryImage", gallaryImageRoute);
router.use("/gallaryCategory", gallaryCategoryRoute);
router.use("/inquiry", inquiryRoute);
router.use("/aboutImage", aboutImageRoute);
router.use("/aboutTabs", aboutTabsRoute);
router.use("/aboutSection", aboutSectionRoute);
router.use("/missionVision", missionvisionRoute);
router.use("/menu", menuRoute);
router.use("/banner", bannerRoute);
router.use("/websiteSetting", websiteSetting);
router.use("/career", careerRoute);
router.use("/tieUpTitle", tieUpTitleRoute);
router.use("/tieUpImage", tieUpImageRoute);
router.use("/bloodDonation", bloodDonationRoute);
router.use("/coreFacilities", coreFacilitiesRoute);
router.use("/homePageBanner", homePageBannerRoute);


export default router;
